server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_client
    username: telegram_client
    password: telegram_client
  jpa:

    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
